<a href="https://colab.research.google.com/github/mustaphamerakech/tpDataScience/blob/main/tpDataScienceML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Charger le fichier Excel
df = pd.read_csv("/content/drive/MyDrive/tpDataScience/jobs_clean.csv")

In [ ]:
df.head()

,company_name,job_name,localisation,publish_date,additional_information,work_shift,experience,extracted_information
0,Sarl Future Motors Algérie,Technicien Engins,"Alger, Algérie",Hier,Mission principale : Le Technicien Engins est...,Confirmé / Expérimenté,3 à 5 ans,"['technicien', 'engins', 'solides', 'diplôme',..."
1,Sarl Future Motors Algérie,Aide Mécanicien,"Alger, Algérie",Hier,Mission principale : Sous la supervision du t...,Confirmé / Expérimenté,3 à 5 ans,"['compétences', 'compétences', 'compétences', ..."
2,Entreprise anonyme,Caissier,"Alger, Algérie",Hier,Mission du Poste : Le caissier est chargé d'as...,Confirmé / Expérimenté,3 à 5 ans,"['principales', 'accueillir', 'fournir', 'info..."
3,Altius Contact,Superviseur dans le domaine de la télévente,"Tizi Ouzou, Algérie",Hier,Nous recherchons un superviseur en télévente e...,Responsable d'équipe,6 à 10 ans,"['compétences', 'équipe', 'expérience', 'compé..."
4,Entreprise anonyme,Coordinateur Trésorerie et Relations Bancaires,"Bab El Oued, Alger, Algérie...",Hier,Missions Principales :Veiller à la solvabilité...,Responsable d'équipe,Plus de 10 ans,"['import', 'audit', 'contrôle', 'hiérarchie', ..."

In [ ]:
df.drop(['additional_information','publish_date'], axis=1, inplace=True)

In [ ]:
from sklearn.preprocessing import LabelEncoder



# Assuming the column you want to encode is named 'your_column'
# Replace 'your_column' with the actual column name in your DataFrame
label_encoder = LabelEncoder()
df['extracted_information_encoded'] = label_encoder.fit_transform(df['extracted_information'])

# Display the DataFrame with the encoded column
df.head()

,company_name,job_name,localisation,work_shift,experience,extracted_information,extracted_information_encoded
0,Sarl Future Motors Algérie,Technicien Engins,"Alger, Algérie",Confirmé / Expérimenté,3 à 5 ans,"['technicien', 'engins', 'solides', 'diplôme',...",1969
1,Sarl Future Motors Algérie,Aide Mécanicien,"Alger, Algérie",Confirmé / Expérimenté,3 à 5 ans,"['compétences', 'compétences', 'compétences', ...",508
2,Entreprise anonyme,Caissier,"Alger, Algérie",Confirmé / Expérimenté,3 à 5 ans,"['principales', 'accueillir', 'fournir', 'info...",1504
3,Altius Contact,Superviseur dans le domaine de la télévente,"Tizi Ouzou, Algérie",Responsable d'équipe,6 à 10 ans,"['compétences', 'équipe', 'expérience', 'compé...",540
4,Entreprise anonyme,Coordinateur Trésorerie et Relations Bancaires,"Bab El Oued, Alger, Algérie...",Responsable d'équipe,Plus de 10 ans,"['import', 'audit', 'contrôle', 'hiérarchie', ...",1146

In [ ]:
df.drop('extracted_information', axis=1, inplace=True)

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder



# Liste des colonnes catégorielles à encoder
categorical_columns = ['company_name', 'job_name', 'localisation', 'work_shift', 'experience']

# Instancier LabelEncoder
label_encoder = LabelEncoder()

# Appliquer LabelEncoder à chaque colonne catégorielle
for col in categorical_columns:
    df[col + '_encoded'] = label_encoder.fit_transform(df[col])

# Maintenant, vous avez des colonnes supplémentaires avec des valeurs encodées
df.drop(['company_name', 'job_name', 'localisation', 'work_shift', 'experience'], axis=1, inplace=True)
df.head()

,extracted_information_encoded,company_name_encoded,job_name_encoded,localisation_encoded,work_shift_encoded,experience_encoded
0,1969,494,1700,8,1,1
1,508,494,105,8,1,1
2,1504,202,274,8,1,1
3,540,46,1657,177,5,2
4,1146,202,668,17,5,4

In [ ]:
# Exemple d'encodage one-hot pour les colonnes catégoriques
categorical_columns = ['company_name','localisation','work_shift','experience']
df_encoded = pd.get_dummies(df, columns=categorical_columns)
# Afficher le DataFrame résultant
df_encoded.head()

,job_name,extracted_information_encoded,company_name_3M Express,company_name_3mexpressReghaia,company_name_AB LIFT,company_name_AB PARK DISCOVERY AND ADVENTURE,company_name_ABCOM,company_name_ACG sim,company_name_AD EVOLUTION - Franchise Oxxo Algérie,company_name_AFC Industry,...,work_shift_ Jeune diplômé,work_shift_ Manager / Responsable département,work_shift_ Responsable d'équipe,work_shift_ Stagiaire / Etudiant,experience_1 à 2 ans,experience_3 à 5 ans,experience_6 à 10 ans,experience_Moins d’un an,experience_Plus de 10 ans,experience_Sans expérience
0,Technicien Engins,1969,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,Aide Mécanicien,508,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,Caissier,1504,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,Superviseur dans le domaine de la télévente,540,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
4,Coordinateur Trésorerie et Relations Bancaires,1146,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [ ]:
X = df_encoded.drop('job_name', axis=1)
X

,extracted_information_encoded,company_name_3M Express,company_name_3mexpressReghaia,company_name_AB LIFT,company_name_AB PARK DISCOVERY AND ADVENTURE,company_name_ABCOM,company_name_ACG sim,company_name_AD EVOLUTION - Franchise Oxxo Algérie,company_name_AFC Industry,company_name_AFRIC HANDASSA,...,work_shift_ Jeune diplômé,work_shift_ Manager / Responsable département,work_shift_ Responsable d'équipe,work_shift_ Stagiaire / Etudiant,experience_1 à 2 ans,experience_3 à 5 ans,experience_6 à 10 ans,experience_Moins d’un an,experience_Plus de 10 ans,experience_Sans expérience
0,1969,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,508,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,1504,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,540,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
4,1146,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,1196,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2396,1261,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2397,1955,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
2398,156,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
2399,1166,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [ ]:
Y = df_encoded.job_name
Y

0                                      Technicien Engins
1                                        Aide Mécanicien
2                                               Caissier
3            Superviseur dans le domaine de la télévente
4         Coordinateur Trésorerie et Relations Bancaires
                              ...
2395                              Responsable de Gestion
2396                              Responsable Commercial
2397                 Responsable des ressources humaines
2398                            Customer Service Manager
2399    Gestionnaire Moyens Généraux & Achats indirectes
Name: job_name, Length: 2400, dtype: object

In [ ]:
from sklearn.feature_selection import VarianceThreshold
selection = VarianceThreshold(threshold=(.8 * (1 - .8)))
X = selection.fit_transform(X)

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [ ]:
model = RandomForestRegressor(n_estimators=100)
model.fit(X_train, Y_train)
r2 = model.score(X_test, Y_test)
r2

ValueError: could not convert string to float: 'Financial Planning & Analysis Controller'